/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.view;

import br.com.dao.RelatorioEnroladoresDAO;
import br.com.dao.RelatorioProducaoDAO;
import br.com.dao.CalculoDAO;
import br.com.entidade.RelatorioEnroladores;
import br.com.entidade.RelatorioProducao;
import br.com.entidade.Calculo;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Aluno
 */
public class frmConsultarRelatorio extends javax.swing.JDialog {
     //Produção
     private final RelatorioProducaoDAO dao1 = new RelatorioProducaoDAO();//Consulta e tabelas
     private final RelatorioProducaoDAO daoRelatorioProducao;//Editar
     private List<RelatorioProducao> relatorioProducao = new LinkedList<RelatorioProducao>();//importa List
     //Enrolação
     private final RelatorioEnroladoresDAO dao2 = new RelatorioEnroladoresDAO();//Consulta e tabelas
     private final RelatorioEnroladoresDAO daoRelatorioEnroladores;//Editar
     private List<RelatorioEnroladores> relatorioEnroladores = new LinkedList<RelatorioEnroladores>();//importa List
     //Calculo
     private final CalculoDAO dao3 = new CalculoDAO();//Consulta e tabelas
     private final CalculoDAO daoCalculo;//Editar
     private List<Calculo> calculo = new LinkedList<Calculo>();//importa List

     private final frmPrincipal control;//Editar
    
    
    public frmConsultarRelatorio(java.awt.Frame parent, boolean modal, RelatorioProducaoDAO daoRelatorioProducao, RelatorioEnroladoresDAO daoRelatorioEnroladores, CalculoDAO daoCalculo, frmPrincipal control) {
        super(parent, modal);
        this.daoRelatorioProducao = daoRelatorioProducao;//Editar
        this.daoRelatorioEnroladores = daoRelatorioEnroladores;//Editar
        this.daoCalculo = daoCalculo;//Editar
        this.control = control;//Editar       
        initComponents();
        loadTableProducao();
        loadTableEnrolacao();
        
        tfQuinzenaProducaoPesquisa.setDocument(new NumerosPermitidos());
        tfQuinzenaEnrolacaoPesquisa.setDocument(new NumerosPermitidos());
        
        tfQuinzenaProducao.setDocument(new NumerosPermitidos());
        tfQuantidadeProducaoGrande.setDocument(new NumerosPermitidos());
        tfQuantidadeProducaoPequena.setDocument(new NumerosPermitidos());
        tfQuantidadeProducaoParadinha.setDocument(new NumerosPermitidos());
        
        tfQuinzenaEnrolacao.setDocument(new NumerosPermitidos());
        tfQuantidadeEnrolacaoGrande.setDocument(new NumerosPermitidos());
        tfQuantidadeEnrolacaoPequena.setDocument(new NumerosPermitidos());
        tfQuantidadeEnrolacaoParadinha.setDocument(new NumerosPermitidos());
        
        tfQuinzenaCalculo.setDocument(new NumerosPermitidos());
        //tfQuantidadeProducaoCalculo.setDocument(new NumerosPermitidos());
        //tfQuantidadeEnrolacaoCalculo.setDocument(new NumerosPermitidos());
        //tfCalculo.setDocument(new NumerosPermitidos());
        tfPassou.setDocument(new TeclasPermitidas());
        
        //calcular
        ftfMesProducao.setEditable(false);
        tfQuinzenaProducao.setEditable(false);
        tfQuantidadeProducaoGrande.setEditable(false);
        tfQuantidadeProducaoPequena.setEditable(false);
        tfQuantidadeProducaoParadinha.setEditable(false);
        
        ftfMesEnrolacao.setEditable(false);
        tfQuinzenaEnrolacao.setEditable(false);
        tfQuantidadeEnrolacaoGrande.setEditable(false);
        tfQuantidadeEnrolacaoPequena.setEditable(false);
        tfQuantidadeEnrolacaoParadinha.setEditable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ftfPesquisaMesFabricacao = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        tfQuinzenaProducaoPesquisa = new javax.swing.JTextField();
        btPesquisarProducao = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ftfMesProducao = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        tfQuinzenaProducao = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfQuantidadeProducaoGrande = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ftfMesEnrolacao = new javax.swing.JFormattedTextField();
        tfQuinzenaEnrolacao = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        tfQuantidadeProducaoPequena = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfQuantidadeProducaoParadinha = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfQuantidadeEnrolacaoGrande = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfQuantidadeEnrolacaoPequena = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tfQuantidadeEnrolacaoParadinha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ftfPesquisaMesEnrolacao = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        tfQuinzenaEnrolacaoPesquisa = new javax.swing.JTextField();
        btPesquisarEnrolacao = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ftfMesCalculo = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        tfQuinzenaCalculo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfQuantidadeProducaoCalculo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfQuantidadeEnrolacaoCalculo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfCalculo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfPassou = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Relatório Final");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Consulta de Relatório Final");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa de Produção"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Pesquisar por Mês da Fabricação .:");

        try {
            ftfPesquisaMesFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfPesquisaMesFabricacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Quinzena .:");

        tfQuinzenaProducaoPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuinzenaProducaoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuinzenaProducaoPesquisaActionPerformed(evt);
            }
        });

        btPesquisarProducao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btPesquisarProducao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.jpg"))); // NOI18N
        btPesquisarProducao.setText("Pesquisar");
        btPesquisarProducao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPesquisarProducao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btPesquisarProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarProducaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ftfPesquisaMesFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfQuinzenaProducaoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btPesquisarProducao, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(ftfPesquisaMesFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfQuinzenaProducaoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                    .addComponent(btPesquisarProducao)
                    .addGap(9, 9, 9)))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Realizar Cálculo"));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mês da Fabricação .:");

        ftfMesProducao.setBackground(new java.awt.Color(204, 204, 204));
        try {
            ftfMesProducao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfMesProducao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Quinzena .:");

        tfQuinzenaProducao.setBackground(new java.awt.Color(204, 204, 204));
        tfQuinzenaProducao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuinzenaProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuinzenaProducaoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Quantidade Grande .:");

        tfQuantidadeProducaoGrande.setBackground(new java.awt.Color(204, 204, 204));
        tfQuantidadeProducaoGrande.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadeProducaoGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeProducaoGrandeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mês da Enrolação .:");

        ftfMesEnrolacao.setBackground(new java.awt.Color(204, 204, 204));
        try {
            ftfMesEnrolacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfMesEnrolacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfQuinzenaEnrolacao.setBackground(new java.awt.Color(204, 204, 204));
        tfQuinzenaEnrolacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuinzenaEnrolacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuinzenaEnrolacaoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Quinzena .:");

        btCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/soma.jpg"))); // NOI18N
        btCalcular.setText("Calcular");
        btCalcular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        tfQuantidadeProducaoPequena.setBackground(new java.awt.Color(204, 204, 204));
        tfQuantidadeProducaoPequena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadeProducaoPequena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeProducaoPequenaActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Quantidade Pequena .:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Quantidade Paradinha .:");

        tfQuantidadeProducaoParadinha.setBackground(new java.awt.Color(204, 204, 204));
        tfQuantidadeProducaoParadinha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadeProducaoParadinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeProducaoParadinhaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Quantidade Grande .:");

        tfQuantidadeEnrolacaoGrande.setBackground(new java.awt.Color(204, 204, 204));
        tfQuantidadeEnrolacaoGrande.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadeEnrolacaoGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeEnrolacaoGrandeActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Quantidade Pequena .:");

        tfQuantidadeEnrolacaoPequena.setBackground(new java.awt.Color(204, 204, 204));
        tfQuantidadeEnrolacaoPequena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadeEnrolacaoPequena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeEnrolacaoPequenaActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Quantidade Paradinha .:");

        tfQuantidadeEnrolacaoParadinha.setBackground(new java.awt.Color(204, 204, 204));
        tfQuantidadeEnrolacaoParadinha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadeEnrolacaoParadinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeEnrolacaoParadinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfQuantidadeProducaoGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel25))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfQuinzenaProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQuantidadeProducaoPequena, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ftfMesProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfQuantidadeProducaoParadinha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259)
                        .addComponent(btCalcular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfQuantidadeEnrolacaoParadinha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfQuantidadeEnrolacaoGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ftfMesEnrolacao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfQuinzenaEnrolacao, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(tfQuantidadeEnrolacaoPequena))
                .addGap(6, 6, 6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQuinzenaProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ftfMesProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(ftfMesEnrolacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQuinzenaEnrolacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQuantidadeProducaoPequena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(tfQuantidadeProducaoGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(tfQuantidadeEnrolacaoGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(tfQuantidadeEnrolacaoPequena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfQuantidadeProducaoParadinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfQuantidadeEnrolacaoParadinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCalcular))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa de Enrolação"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Pesquisar por Mês da Enrolação .:");

        try {
            ftfPesquisaMesEnrolacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfPesquisaMesEnrolacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Quinzena .:");

        tfQuinzenaEnrolacaoPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuinzenaEnrolacaoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuinzenaEnrolacaoPesquisaActionPerformed(evt);
            }
        });

        btPesquisarEnrolacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btPesquisarEnrolacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.jpg"))); // NOI18N
        btPesquisarEnrolacao.setText("Pesquisar");
        btPesquisarEnrolacao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPesquisarEnrolacao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btPesquisarEnrolacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarEnrolacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftfPesquisaMesEnrolacao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfQuinzenaEnrolacaoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPesquisarEnrolacao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftfPesquisaMesEnrolacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQuinzenaEnrolacaoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btPesquisarEnrolacao)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Salvar Cálculo"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Mês .:");

        try {
            ftfMesCalculo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfMesCalculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Quinzena .:");

        tfQuinzenaCalculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuinzenaCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuinzenaCalculoActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Quantidade da Produção .:");

        tfQuantidadeProducaoCalculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadeProducaoCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeProducaoCalculoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Quantidade da Enrolação .:");

        tfQuantidadeEnrolacaoCalculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadeEnrolacaoCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeEnrolacaoCalculoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Cálculo .:");

        tfCalculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCalculoActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Passou em .:");

        tfPassou.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfPassou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassouActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.jpg"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfQuinzenaCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfMesCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfQuantidadeEnrolacaoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfQuantidadeProducaoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPassou, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addGap(18, 18, 18)
                .addComponent(btSalvar)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftfMesCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQuantidadeProducaoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(tfCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQuinzenaCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tfQuantidadeEnrolacaoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tfPassou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btLimpar)))
        );

        btVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back-icon.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVoltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfQuinzenaProducaoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuinzenaProducaoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuinzenaProducaoPesquisaActionPerformed

    private void btPesquisarProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarProducaoActionPerformed
        String pesquisa_mes_pro = ftfPesquisaMesFabricacao.getText();

        if(pesquisa_mes_pro.equals("  /    ")){
            JOptionPane.showMessageDialog(this, "O campo PESQUISAR POR MÊS DA FABRICAÇÃO não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }

        if(tfQuinzenaProducaoPesquisa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo QUINZENA não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                Pesquisa_loadInitialDataProducao();
                setCampos_PesquisaProducao();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao Pesquisar a Produção", "ERRO" + ex, JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btPesquisarProducaoActionPerformed

    private void tfQuinzenaEnrolacaoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuinzenaEnrolacaoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuinzenaEnrolacaoPesquisaActionPerformed

    private void btPesquisarEnrolacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarEnrolacaoActionPerformed
        String pesquisa_mes_enro = ftfPesquisaMesEnrolacao.getText();

        if(pesquisa_mes_enro.equals("  /    ")){
            JOptionPane.showMessageDialog(this, "O campo PESQUISAR POR MÊS DA ENROLAÇÃO não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }

        if(tfQuinzenaEnrolacaoPesquisa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo QUINZENA não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                Pesquisa_loadInitialDataEnrolacao();
                setCampos_PesquisaEnrolacao();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao Pesquisar a Enrolação", "ERRO" + ex, JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btPesquisarEnrolacaoActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void tfQuinzenaProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuinzenaProducaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuinzenaProducaoActionPerformed

    private void tfQuantidadeProducaoGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeProducaoGrandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeProducaoGrandeActionPerformed

    private void tfQuinzenaEnrolacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuinzenaEnrolacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuinzenaEnrolacaoActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
           calcular();  
    }//GEN-LAST:event_btCalcularActionPerformed

    private void tfQuinzenaCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuinzenaCalculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuinzenaCalculoActionPerformed

    private void tfQuantidadeProducaoCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeProducaoCalculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeProducaoCalculoActionPerformed

    private void tfQuantidadeEnrolacaoCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeEnrolacaoCalculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeEnrolacaoCalculoActionPerformed

    private void tfCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCalculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCalculoActionPerformed

    private void tfPassouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassouActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
    ftfMesCalculo.setText("");
    tfQuinzenaCalculo.setText("");
    tfQuantidadeProducaoCalculo.setText("");
    tfQuantidadeEnrolacaoCalculo.setText("");
    tfCalculo.setText("");
    tfPassou.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
       String mes_calculo = ftfMesCalculo.getText();

        if(mes_calculo.equals("  /    ")){
            JOptionPane.showMessageDialog(this, "O campo MÊS não está formatado", "Validação", JOptionPane.ERROR_MESSAGE );
        }

        if(tfQuinzenaCalculo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo QUINZENA não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }

        if(tfQuantidadeProducaoCalculo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo QUANTIDADE DA PRODUÇÃO não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }

        if(tfQuantidadeEnrolacaoCalculo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo QUANTIDADE DA ENROLAÇÃO não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }
        
        if(tfCalculo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo CALCULO não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }
        
        if(tfPassou.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo PASSOU EM não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }
        else {
            int b = JOptionPane.showConfirmDialog(null, "Deseja Cadastrar o Cálculo?" , "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (b == 0){
                try{
                    Calculo calculo = new Calculo();
                    calculo.setMes(mes_calculo);
                    calculo.setQuinzena(tfQuinzenaCalculo.getText());
                    calculo.setQuantidade_producao(tfQuantidadeProducaoCalculo.getText());
                    calculo.setQuantidade_enrolacao(tfQuantidadeEnrolacaoCalculo.getText());
                    calculo.setCalculo(tfCalculo.getText());
                    calculo.setPassou(tfPassou.getText());
                    dao3.addCalculo(calculo);
                    JOptionPane.showMessageDialog(this, "Cálculo Cadastrada com SUCESSO!" , "SUCESSO" , JOptionPane.INFORMATION_MESSAGE);
                    setCamposSalvar();
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Erro ao Cadastrar o Cálculo", "ERRO" + ex, JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfQuantidadeProducaoPequenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeProducaoPequenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeProducaoPequenaActionPerformed

    private void tfQuantidadeProducaoParadinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeProducaoParadinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeProducaoParadinhaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int linha_selecionada = jTable1.getSelectedRow(); //Pegar a linha selecionada.
       
       //Calcular
       ftfMesProducao.setText(jTable1.getValueAt(linha_selecionada, 0).toString());
       tfQuinzenaProducao.setText(jTable1.getValueAt(linha_selecionada, 1).toString());
       tfQuantidadeProducaoGrande.setText(jTable1.getValueAt(linha_selecionada, 2).toString());
       tfQuantidadeProducaoPequena.setText(jTable1.getValueAt(linha_selecionada, 3).toString());
       tfQuantidadeProducaoParadinha.setText(jTable1.getValueAt(linha_selecionada, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int linha_selecionada1 = jTable2.getSelectedRow(); //Pegar a linha selecionada.
       
       //Calcular
       ftfMesEnrolacao.setText(jTable2.getValueAt(linha_selecionada1, 0).toString());
       tfQuinzenaEnrolacao.setText(jTable2.getValueAt(linha_selecionada1, 1).toString());
       tfQuantidadeEnrolacaoGrande.setText(jTable2.getValueAt(linha_selecionada1, 2).toString());
       tfQuantidadeEnrolacaoPequena.setText(jTable2.getValueAt(linha_selecionada1, 3).toString());
       tfQuantidadeEnrolacaoParadinha.setText(jTable2.getValueAt(linha_selecionada1, 4).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void tfQuantidadeEnrolacaoGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeEnrolacaoGrandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeEnrolacaoGrandeActionPerformed

    private void tfQuantidadeEnrolacaoPequenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeEnrolacaoPequenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeEnrolacaoPequenaActionPerformed

    private void tfQuantidadeEnrolacaoParadinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeEnrolacaoParadinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeEnrolacaoParadinhaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisarEnrolacao;
    private javax.swing.JButton btPesquisarProducao;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JFormattedTextField ftfMesCalculo;
    private javax.swing.JFormattedTextField ftfMesEnrolacao;
    private javax.swing.JFormattedTextField ftfMesProducao;
    private javax.swing.JFormattedTextField ftfPesquisaMesEnrolacao;
    private javax.swing.JFormattedTextField ftfPesquisaMesFabricacao;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField tfCalculo;
    private javax.swing.JTextField tfPassou;
    private javax.swing.JTextField tfQuantidadeEnrolacaoCalculo;
    private javax.swing.JTextField tfQuantidadeEnrolacaoGrande;
    private javax.swing.JTextField tfQuantidadeEnrolacaoParadinha;
    private javax.swing.JTextField tfQuantidadeEnrolacaoPequena;
    private javax.swing.JTextField tfQuantidadeProducaoCalculo;
    private javax.swing.JTextField tfQuantidadeProducaoGrande;
    private javax.swing.JTextField tfQuantidadeProducaoParadinha;
    private javax.swing.JTextField tfQuantidadeProducaoPequena;
    private javax.swing.JTextField tfQuinzenaCalculo;
    private javax.swing.JTextField tfQuinzenaEnrolacao;
    private javax.swing.JTextField tfQuinzenaEnrolacaoPesquisa;
    private javax.swing.JTextField tfQuinzenaProducao;
    private javax.swing.JTextField tfQuinzenaProducaoPesquisa;
    // End of variables declaration//GEN-END:variables

//Producao    
    public void Pesquisa_loadInitialDataProducao() {
        try {
            String pesquisa_mes_pro = ftfPesquisaMesFabricacao.getText();
            RelatorioProducao rela_pro = new RelatorioProducao();
            rela_pro.setMes_fabricacao(pesquisa_mes_pro);
            rela_pro.setQuinzena(tfQuinzenaProducaoPesquisa.getText());
            relatorioProducao = dao1.searchRelatorioProducao(rela_pro.getMes_fabricacao(), rela_pro.getQuinzena());
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }        
        jTable1.setModel(new MyTableModel(RelatorioProducao.class, relatorioProducao, jTable1));
        
    }

public void loadTableProducao() {
    try {
        relatorioProducao = dao1.loadTableProducao();
    }catch (Exception ex) {
            ex.printStackTrace();
        }        
        jTable1.setModel(new MyTableModel(RelatorioProducao.class, relatorioProducao, jTable1));
}
    
//Enrolação    
     public void Pesquisa_loadInitialDataEnrolacao() {
        try {
            String pesquisa_mes_enro = ftfPesquisaMesEnrolacao.getText();
            RelatorioEnroladores rela_enro = new RelatorioEnroladores();
            rela_enro.setMes_enrolacao(pesquisa_mes_enro);
            rela_enro.setQuinzena(tfQuinzenaEnrolacaoPesquisa.getText());
            relatorioEnroladores = dao2.searchRelatorioEnroladores(rela_enro.getMes_enrolacao(), rela_enro.getQuinzena());
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }        
        jTable2.setModel(new MyTableModel(RelatorioEnroladores.class, relatorioEnroladores, jTable2));
        
    }

public void loadTableEnrolacao() {
    try {
        relatorioEnroladores = dao2.loadTableEnroladores();
    }catch (Exception ex) {
            ex.printStackTrace();
        }        
        jTable2.setModel(new MyTableModel(RelatorioEnroladores.class, relatorioEnroladores, jTable2));
}
    
    
    
public void setCamposSalvar() {
    //Limpa os campos do Realizar Cálculo
    ftfMesProducao.setText("");
    tfQuinzenaProducao.setText("");
    tfQuantidadeProducaoGrande.setText("");
    tfQuantidadeProducaoPequena.setText("");
    tfQuantidadeProducaoParadinha.setText("");
    
    ftfMesEnrolacao.setText("");
    tfQuinzenaEnrolacao.setText("");
    tfQuantidadeEnrolacaoGrande.setText("");
    tfQuantidadeEnrolacaoPequena.setText("");
    tfQuantidadeEnrolacaoParadinha.setText("");
    
    //Limpa os campos do Salvar Cálculo
    ftfMesCalculo.setText("");
    tfQuinzenaCalculo.setText("");
    tfQuantidadeProducaoCalculo.setText("");
    tfQuantidadeEnrolacaoCalculo.setText("");
    tfCalculo.setText("");
    tfPassou.setText("");
    
}

public void setCampos_PesquisaProducao() {
    ftfPesquisaMesFabricacao.setText("");
    tfQuinzenaProducaoPesquisa.setText("");
}
    
public void setCampos_PesquisaEnrolacao() {
    ftfPesquisaMesEnrolacao.setText("");
    tfQuinzenaEnrolacaoPesquisa.setText("");
}

public void calcular(){
        String mes_producao = ftfMesProducao.getText();
        String mes_enrolacao = ftfMesEnrolacao.getText();
        String quinzena_pro = tfQuinzenaProducao.getText();
        String quinzena_enro = tfQuinzenaEnrolacao.getText();        
        
        if (mes_producao.equals(mes_enrolacao) && quinzena_pro.equals(quinzena_enro)){
            ftfMesCalculo.setText(mes_producao);
            tfQuinzenaCalculo.setText(tfQuinzenaProducao.getText());
            
            //produção
            double quantidade_grande_pro = Double.parseDouble(tfQuantidadeProducaoGrande.getText());
            double quantidade_pequena_pro = Double.parseDouble(tfQuantidadeProducaoPequena.getText());
            double quantidade_paradinha_pro = Double.parseDouble(tfQuantidadeProducaoParadinha.getText());
        
            double resultado_producao = quantidade_grande_pro + quantidade_pequena_pro + quantidade_paradinha_pro;
            tfQuantidadeProducaoCalculo.setText(String.valueOf(resultado_producao));
            
            //enrolação
            double quantidade_grande_enro = Double.parseDouble(tfQuantidadeEnrolacaoGrande.getText());
            double quantidade_pequena_enro = Double.parseDouble(tfQuantidadeEnrolacaoPequena.getText());
            double quantidade_paradinha_enro = Double.parseDouble(tfQuantidadeEnrolacaoParadinha.getText());
            
            double resultado_enrolacao = quantidade_grande_enro + quantidade_pequena_enro + quantidade_paradinha_enro;
            tfQuantidadeEnrolacaoCalculo.setText(String.valueOf(resultado_enrolacao));
            
            //Passou
            double quantidade_enro_calc = Double.parseDouble(tfQuantidadeEnrolacaoCalculo.getText());
            double quantidade_pro_calc = Double.parseDouble(tfQuantidadeProducaoCalculo.getText());
            
            double calculo_result = quantidade_pro_calc - quantidade_enro_calc;
            
            tfCalculo.setText(String.valueOf(calculo_result));
        } else {
            JOptionPane.showMessageDialog(this, "Os MESES ou as QUINZENAS não conrespondem", "Validação", JOptionPane.ERROR_MESSAGE);

        } 
}

}
