/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.view;

import br.com.dao.SomaDAO;
import br.com.dao.SomaConsultaDAO;
import br.com.entidade.Soma;
import br.com.entidade.SomaConsulta;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class frmSomaCadeirasEnrol extends javax.swing.JDialog {
     //Realizar e Pesquisar Soma
     private final SomaDAO dao = new SomaDAO();//Consulta e tabelas
     private final SomaDAO daoSoma;//Editar
     private List<Soma> soma = new LinkedList<Soma>();//importa List
     
     //Salvar Soma
     private final SomaConsultaDAO dao1 = new SomaConsultaDAO();//Consulta e tabelas
     private final SomaConsultaDAO daoSomaConsulta;//Editar
     private List<SomaConsulta> somaConsulta = new LinkedList<SomaConsulta>();//importa List
     
     private final frmPrincipal control;//Editar
   
    public frmSomaCadeirasEnrol(java.awt.Frame parent, boolean modal, SomaDAO daoSoma, SomaConsultaDAO daoSomaConsulta, frmPrincipal control) {
        super(parent, modal);
        this.daoSoma = daoSoma;//Editar
        this.daoSomaConsulta = daoSomaConsulta;//Editar
        this.control = control;//Editar
        initComponents();
        loadTable();
        tfIdEnroladorPesquisa.setDocument(new NumerosPermitidos());
        tfQuinzenaPesquisa.setDocument(new NumerosPermitidos());
        
        //Realizar Somar    
        tfIdEnrolador.setDocument(new NumerosPermitidos());
        tfQuinzena.setDocument(new NumerosPermitidos());
        tfQuantidadeGrande.setDocument(new NumerosPermitidos());
        tfQuantidadePequena.setDocument(new NumerosPermitidos());
        tfQuantidadeParadinha.setDocument(new NumerosPermitidos());
        
        //Salvar Soma
        tfIdEnroladorSoma.setDocument(new NumerosPermitidos());
        tfQuinzenaSoma.setDocument(new NumerosPermitidos());
        
        //Enables
        tfIdEnrolador.setEditable(false);
        ftfMesEnrolacao.setEditable(false);
        tfQuinzena.setEditable(false);
        tfQuantidadeGrande.setEditable(false);
        tfQuantidadePequena.setEditable(false);
        tfQuantidadeParadinha.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        tfIdEnroladorPesquisa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ftfPesquisaMesEnrolacao = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        tfQuinzenaPesquisa = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tfIdEnrolador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ftfMesEnrolacao = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        tfQuinzena = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfQuantidadeGrande = new javax.swing.JTextField();
        btSomar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfQuantidadePequena = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfQuantidadeParadinha = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tfIdEnroladorSoma = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ftfMesEnrolacaoSoma = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        tfQuinzenaSoma = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfSoma = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sama de Cadeiras dos Enroladores - Pagamento");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Soma de Cadeiras dos Enroladores");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("- Pagamento -");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(274, 274, 274))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Somar"));

        tfIdEnroladorPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfIdEnroladorPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdEnroladorPesquisaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("ID Enrolador .:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Pesquisar por Mês da Enrolação .:");

        try {
            ftfPesquisaMesEnrolacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfPesquisaMesEnrolacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Quinzena .:");

        tfQuinzenaPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuinzenaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuinzenaPesquisaActionPerformed(evt);
            }
        });

        btPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.jpg"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfIdEnroladorPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftfPesquisaMesEnrolacao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfQuinzenaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPesquisar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdEnroladorPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel4)
                    .addComponent(ftfPesquisaMesEnrolacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQuinzenaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btPesquisar))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Realizar Soma"));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("ID Enrolador .:");

        tfIdEnrolador.setBackground(new java.awt.Color(204, 204, 204));
        tfIdEnrolador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfIdEnrolador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdEnroladorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mês da Enrolação .:");

        ftfMesEnrolacao.setBackground(new java.awt.Color(204, 204, 204));
        try {
            ftfMesEnrolacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfMesEnrolacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ftfMesEnrolacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfMesEnrolacaoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Quinzena .:");

        tfQuinzena.setBackground(new java.awt.Color(204, 204, 204));
        tfQuinzena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuinzena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuinzenaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Quantidade Grande .:");

        tfQuantidadeGrande.setBackground(new java.awt.Color(204, 204, 204));
        tfQuantidadeGrande.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadeGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeGrandeActionPerformed(evt);
            }
        });

        btSomar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSomar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/soma.jpg"))); // NOI18N
        btSomar.setText("Somar");
        btSomar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSomar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSomarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Quantidade Pequena .:");

        tfQuantidadePequena.setBackground(new java.awt.Color(204, 204, 204));
        tfQuantidadePequena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadePequena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadePequenaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Quantidade Paradinha .:");

        tfQuantidadeParadinha.setBackground(new java.awt.Color(204, 204, 204));
        tfQuantidadeParadinha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuantidadeParadinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeParadinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSomar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(tfIdEnrolador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftfMesEnrolacao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfQuinzena, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfQuantidadeGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQuantidadeParadinha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQuantidadePequena, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdEnrolador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8)
                    .addComponent(tfQuantidadeGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftfMesEnrolacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfQuantidadePequena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfQuinzena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfQuantidadeParadinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSomar))
        );

        btVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back-icon.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Salvar Soma"));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("ID Enrolador .:");

        tfIdEnroladorSoma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfIdEnroladorSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdEnroladorSomaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Mês da Enrolação .:");

        try {
            ftfMesEnrolacaoSoma.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfMesEnrolacaoSoma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ftfMesEnrolacaoSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfMesEnrolacaoSomaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Quinzena .:");

        tfQuinzenaSoma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfQuinzenaSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuinzenaSomaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Soma .:");

        tfSoma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSomaActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.jpg"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(tfIdEnroladorSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(ftfMesEnrolacaoSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQuinzenaSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvar)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdEnroladorSoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(tfQuinzenaSoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftfMesEnrolacaoSoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfSoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btLimpar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVoltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdEnroladorPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdEnroladorPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdEnroladorPesquisaActionPerformed

    private void tfQuinzenaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuinzenaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuinzenaPesquisaActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        String pesquisa_mes_enro = ftfPesquisaMesEnrolacao.getText();

        if(tfIdEnroladorPesquisa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo ID ENROLADOR não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }

        if(pesquisa_mes_enro.equals("  /    ")){
            JOptionPane.showMessageDialog(this, "O campo PESQUISAR POR MÊS DA ENROLAÇÃO não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }

        if(tfQuinzenaPesquisa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo QUINZENA não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                Pesquisa_loadInitialData();
                setCampos_Pesquisa();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao Pesquisar a Produção", "ERRO" + ex, JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void tfIdEnroladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdEnroladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdEnroladorActionPerformed

    private void ftfMesEnrolacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfMesEnrolacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfMesEnrolacaoActionPerformed

    private void tfQuinzenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuinzenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuinzenaActionPerformed

    private void tfQuantidadeGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeGrandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeGrandeActionPerformed

    private void btSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomarActionPerformed
        somar();
    }//GEN-LAST:event_btSomarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int linha_selecionada = jTable1.getSelectedRow(); //Pegar a linha selecionada.
       
       //Editar
       tfIdEnrolador.setText(jTable1.getValueAt(linha_selecionada, 0).toString());
       ftfMesEnrolacao.setText(jTable1.getValueAt(linha_selecionada, 1).toString());
       tfQuinzena.setText(jTable1.getValueAt(linha_selecionada, 2).toString());
       tfQuantidadeGrande.setText(jTable1.getValueAt(linha_selecionada, 3).toString());
       tfQuantidadePequena.setText(jTable1.getValueAt(linha_selecionada, 4).toString());
       tfQuantidadeParadinha.setText(jTable1.getValueAt(linha_selecionada, 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void tfQuantidadePequenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadePequenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadePequenaActionPerformed

    private void tfQuantidadeParadinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeParadinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeParadinhaActionPerformed

    private void tfIdEnroladorSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdEnroladorSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdEnroladorSomaActionPerformed

    private void ftfMesEnrolacaoSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfMesEnrolacaoSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfMesEnrolacaoSomaActionPerformed

    private void tfQuinzenaSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuinzenaSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuinzenaSomaActionPerformed

    private void tfSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSomaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
    tfIdEnroladorSoma.setText("");
    ftfMesEnrolacaoSoma.setText("");
    tfQuinzenaSoma.setText("");
    tfSoma.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String mes_enrolacao_soma = ftfMesEnrolacaoSoma.getText();

        if(tfIdEnroladorSoma.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo ID ENROLADOR não está formatado", "Validação", JOptionPane.ERROR_MESSAGE );
        }

        if(mes_enrolacao_soma.equals("  /    ")){
            JOptionPane.showMessageDialog(this, "O campo MÊS DA ENROLAÇÃO não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }

        if(tfQuinzenaSoma.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo QUINZENA não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }

        if(tfSoma.getText().equals("")){
            JOptionPane.showMessageDialog(this, "O campo SOMA não está formatado", "Validação", JOptionPane.ERROR_MESSAGE);
        }
        else {
            int b = JOptionPane.showConfirmDialog(null, "Deseja Cadastrar a Soma?" , "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (b == 0){
                try{
                    SomaConsulta somaConsulta = new SomaConsulta();
                    somaConsulta.setId_enrolador(tfIdEnrolador.getText());
                    somaConsulta.setMes_enrolacao(mes_enrolacao_soma);                    
                    somaConsulta.setQuinzena(tfQuinzena.getText());
                    somaConsulta.setSoma(tfSoma.getText());                    
                    daoSomaConsulta.addSoma(somaConsulta);
                    JOptionPane.showMessageDialog(this, "Soma Cadastrada com SUCESSO!" , "SUCESSO" , JOptionPane.INFORMATION_MESSAGE);
                    setCampos();
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Erro ao Cadastrar a Soma", "ERRO" + ex, JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSomar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JFormattedTextField ftfMesEnrolacao;
    private javax.swing.JFormattedTextField ftfMesEnrolacaoSoma;
    private javax.swing.JFormattedTextField ftfPesquisaMesEnrolacao;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfIdEnrolador;
    private javax.swing.JTextField tfIdEnroladorPesquisa;
    private javax.swing.JTextField tfIdEnroladorSoma;
    private javax.swing.JTextField tfQuantidadeGrande;
    private javax.swing.JTextField tfQuantidadeParadinha;
    private javax.swing.JTextField tfQuantidadePequena;
    private javax.swing.JTextField tfQuinzena;
    private javax.swing.JTextField tfQuinzenaPesquisa;
    private javax.swing.JTextField tfQuinzenaSoma;
    private javax.swing.JTextField tfSoma;
    // End of variables declaration//GEN-END:variables
public void Pesquisa_loadInitialData() {
        try {
            String pesquisa_mes_enro = ftfPesquisaMesEnrolacao.getText();
            Soma som = new Soma();
            som.setId_enrolador(tfIdEnroladorPesquisa.getText());
            som.setMes_enrolacao(pesquisa_mes_enro);
            som.setQuinzena(tfQuinzenaPesquisa.getText());
            soma = dao.searchSoma(som.getId_enrolador(), som.getMes_enrolacao(), som.getQuinzena());
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }        
        jTable1.setModel(new MyTableModel(Soma.class, soma, jTable1));
        
    }

public void loadTable() {
    try {
        soma = dao.loadTtable();
    }catch (Exception ex) {
            ex.printStackTrace();
        }        
        jTable1.setModel(new MyTableModel(Soma.class, soma, jTable1));
}

    
public void setCampos() {
    //Limpa os campos Quanto Salvar (Limpa realizar e somar)
    
    //Realizar
    tfIdEnrolador.setText("");
    ftfMesEnrolacao.setText("");
    tfQuinzena.setText("");
    tfQuantidadeGrande.setText("");
    tfQuantidadePequena.setText("");
    tfQuantidadeParadinha.setText("");
    
    //Somar
    tfIdEnroladorSoma.setText("");
    ftfMesEnrolacaoSoma.setText("");
    tfQuinzenaSoma.setText("");
    tfSoma.setText("");
}

public void setCampos_Pesquisa() {
    tfIdEnroladorPesquisa.setText("");
    ftfPesquisaMesEnrolacao.setText("");
    tfQuinzenaPesquisa.setText("");
}

public void somar(){
        String mes_enrolacao = ftfMesEnrolacao.getText();        
        
        tfIdEnroladorSoma.setText(tfIdEnrolador.getText());
        ftfMesEnrolacaoSoma.setText(mes_enrolacao);
        tfQuinzenaSoma.setText(tfQuinzena.getText());
        
        double quantidade_grande = Double.parseDouble(tfQuantidadeGrande.getText());
        double quantidade_pequena = Double.parseDouble(tfQuantidadePequena.getText());
        double quantidade_paradinha = Double.parseDouble(tfQuantidadeParadinha.getText());
        
        double soma = quantidade_grande + quantidade_pequena + quantidade_paradinha;
        tfSoma.setText(String.valueOf(soma));
                       
}

}
